name: Deploy to Google Cloud

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/main.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Poetry
      run: |
        pip install poetry
    
        
    - name: Install dependencies
      run: |
        cd backend
        poetry install
    


    - name: Create .env file
      run: |
        cd backend
        echo "INFOBIP_KEY=${{ secrets.INFOBIP_KEY }}" >> backend/.env
        echo "INFOBIP_URL=${{ secrets.INFOBIP_URL }}" >> backend/.env
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> backend/.env
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> backend/.env
        echo "OPENAI_ENDPOINT=${{ secrets.OPENAI_ENDPOINT }}" >> backend/.env

    - name: Custom SCP to Server
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H "$SERVER_IP" >> ~/.ssh/known_hosts
        scp -r backend/ $SERVER_USER@$SERVER_IP:/home/omarcodes2/pawnder/backend

    - name: Deploy application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: '22'
        script: |
          cd /pwndr/backend/backend
          poetry run uvicorn main:app --host 0.0.0.0 --port 8000
